apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-example
  namespace: argo # namespace where the ArgoCD application controller is running, this is where the application CRD is defined
spec:
  project: default
  source:
    repoURL: 'https://github.com/anmobor2/my-k8s-config-argocd.git'
    targetRevision: HEAD
    path: k8s/nginx
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default # namespace where the application resources should be deployed
  syncPolicy:
    automated:
      prune: true # if a resource is removed from git, delete it from the cluster automatically to keep the cluster in sync with git
      selfHeal: false # if a resource is changed outside of git, overwrite it with the version in git
